version: '3.1'

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo

  quartzer:
    image: quartzer:latest
    ports:
      - 8080:8080
      - 5005:5005
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/test-db


volumes:
  mongodb_data:
